### PR TITLE
Add ADIF data export

### PR DESCRIPTION
**Pull request by ntoskrnl4**
some random notes:
 - sorry about some of the commit messages
 - `adx.py` is in a folder `exports/` because we can then add other export forms in the future
 - `perf_adx.py` is a completely independent script, not a test, but I figured `tests/` would be the best place to put it
 - please run `perf_adx.py` and post what your performance results are

here are my results from `perf_adx.py` (and system specs):
```
Entries in list: 8192
Fields per entry: 100
Total data points: 819200
Total export time: 4.400646711 seconds
Time per entry: 0.537188 ms
Time per data point: 5.3719 us

AMD FX 6300 @ 4.414GHz
(no other specs matter here)
```
results from my Raspberry Pi (+ specs):
```
Entries in list: 8192
Fields per entry: 100
Total data points: 819200
Total export time: 57.728988703 seconds
Time per entry: 7.046996 ms
Time per data point: 70.4700 us

Raspberry Pi 2 @ 900MHz
```

### CODE REVIEW

**Comment by galengold** [comment]
```
Entries in list: 8192
Fields per entry: 100
Total data points: 819200
Total export time: 2.049751540 seconds
Time per entry: 0.250214 ms
Time per data point: 2.5021 us

CPU: Intel i7-7600U (4) @ 3.900GHz
```

**Comment by thisguyistotallyben** [comment]
Here's my stats:

Data export complete! Statistics:

Entries in list: 8192
Fields per entry: 100
Total data points: 819200
Total export time: 9.656407236 seconds
Time per entry: 1.178761 ms
Time per data point: 11.7876 us

Specs:
AMD A8-4500M, 4 cores @ 1.9 GHz

**Comment by galengold** [comment]
```
Entries in list: 8192
Fields per entry: 100
Total data points: 819200
Total export time: 2.197575610 seconds
Time per entry: 0.268259 ms
Time per data point: 2.6826 us

CPU: Intel i5-6600K (4) @ 3.900GHz
```

**Comment by ntoskrnl4** [comment]
stats from my craptop:
```
Data export complete! Statistics:

Entries in list: 8192
Fields per entry: 100
Total data points: 819200
Total export time: 25.799704394 seconds
Time per entry: 3.149378 ms
Time per data point: 31.4938 us

AMD E-300 APU dual core @ 1.3 GHz
```

**Pull request merged**
