### PR TITLE
add ability to import .adx files

### PR DESCRIPTION
**Pull request by ntoskrnl4**
This should be good to merge, I think. I probably need more unit tests, but for right now we can probably go ahead and merge these.

### CODE REVIEW

**Comment by ntoskrnl4** [comment]
From what I can tell from the performance test script, file import is about 4x faster than export.
```
Total export time: 2.192865173 seconds
Total import time: 0.504102535 seconds
```

**Comment by dargasea** [comment]
Can you add code for tearing down so temporary files are removed at the end of the tests?

**Comment by ntoskrnl4** [comment]
`74e7a30` adds those, thanks for the suggestion.

**Comment by dargasea** [comment]
All tests run and some tinkering around shows that the class works as advertised. This PR LGTM.

A PR will come later to throw an exception when an import mode method is called in export mode, and vice versa.

**Pull request merged**
